-- CoFilmery D1 Migration: 0005_assets_table
-- Tracks files uploaded to R2 (images, audio, video) per project

CREATE TABLE IF NOT EXISTS assets (
  id          TEXT PRIMARY KEY,          -- UUID generated by Worker
  project_id  TEXT NOT NULL,             -- links to projects.id (or 'global' for standalone uploads)
  user_id     TEXT NOT NULL,             -- uploader
  file_name   TEXT NOT NULL,             -- original filename
  file_type   TEXT NOT NULL,             -- MIME type (image/jpeg, video/mp4, audio/mpeg …)
  file_size   INTEGER NOT NULL DEFAULT 0,-- bytes
  r2_key      TEXT NOT NULL UNIQUE,      -- full R2 object key (e.g. staging/proj-id/uuid.jpg)
  file_url    TEXT NOT NULL,             -- public URL or /api/assets/file/:key
  category    TEXT NOT NULL DEFAULT 'other'
              CHECK(category IN ('character','scene','prop','sponsor','audio','video','other')),
  label       TEXT,                      -- optional human label / caption
  uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_assets_project ON assets(project_id);
CREATE INDEX IF NOT EXISTS idx_assets_user    ON assets(user_id);
CREATE INDEX IF NOT EXISTS idx_assets_cat     ON assets(project_id, category);
